name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build IPA (unsigned)
        run: |
          cd ios
          xcodebuild \
            -scheme ios-info-app \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ios-info-app.xcarchive archive
          xcodebuild \
            -exportArchive \
            -archivePath build/ios-info-app.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-info-app
          path: ios/build/*.ipa
