name: Build unsigned iOS IPA

on:
  workflow_dispatch: # 手動で実行可能

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install React Native CLI
        run: npm install -g react-native-cli

      - name: Initialize React Native iOS project
        run: |
          npx react-native init ios-info-app --version 0.73.0
          # コピーする場合は App.js を上書き
          cp ../App.js ./ios-info-app/App.js

      - name: Install project dependencies
        run: |
          cd ios-info-app
          npm install
          npm install react-native-device-info
          npx pod-install ios

      - name: Build unsigned IPA
        run: |
          cd ios-info-app/ios
          xcodebuild \
            -scheme ios-info-app \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ios-info-app.xcarchive archive \
            CODE_SIGNING_ALLOWED=NO
          
          xcodebuild -exportArchive \
            -archivePath build/ios-info-app.xcarchive \
            -exportPath build \
            -exportOptionsPlist ../../exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-info-app-unsigned
          path: ios-info-app/ios/build/*.ipa
